### ISSUE TITLE
Review the About/Support page

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-prototype-kit-docs#140]
**What** 
It's not clear that support is on the About page (#865) and the About page has some fairly unconnected stuff on it
More content needs to be added to the About/support page

**Why**
As a new user, it would be helpful to know more about what the Kit looks like and how it works before I download everything, so I know what to expect and know it is something I would use
As a user, I want to be able to persuade my non-coding colleagues to use the Prototype Kit
So that we can all be using the same tool

**Who needs to work on this**
Content Designer 

**Done when**

```[tasklist]
### Tasks
- [x] Describe who the Kit is for and what skills are needed
- [x] Provide guidance and links to other training materials
- [ ] Content & visuals on what the Kit can and can't do
- [x] Describe how the Kit differs to other prototyping tools
- [x] Describe who the Kit is for
- [x] Provide a list of prerequisite skills required to use the Kit effectively
- [ ] Provide examples of hosted prototypes
```

MVP ideas: https://docs.google.com/document/d/1vlpuiNhbRNIjdDQ1kx-MHvlyyLdndR_yvAlcr2ydiDo/edit#heading=h.ymnoc4y8f4vb

New site ideas: https://docs.google.com/document/d/1mMpwDA6NBWkWYzVtaFQ3sd0rtVov56yQw16ollEv5b8/edit#

PRs:

https://github.com/alphagov/govuk-prototype-kit-docs/pull/237

https://github.com/alphagov/govuk-prototype-kit-docs/pull/236

**Comment by oli-rose28** [comment]
@ruthhammond @joelanman I'll move this to done, as we've published the about and support page. The only points we haven't covered are:

- Content & visuals on what the Kit can and can't do (I think we should cover this in the new docs site)
- Provide guidance and links to other training materials (this is covered by #200)
- Provide examples of hosted prototypes (covered by the plugins work)
